### ISSUE TITLE
How to handle additional arguments - add manually addQueryString to the partial?

### ISSUE THREAD

**Issue by sksksksk** [georgringer/numbered_pagination#17]
I am struggling with numbered_pagination on how to handle additional arguments in the generated links. 

The links generated by numbered_pagination have arguments for my controller and action, but I need an additional argument (something like a filter). The additional argument is present in my currently viewed page. But it is not present in the generated links, and I am not sure whether it was supposed to be present or I am missing something. 

Adding addQueryString to all f:uri.action links fixes the problem.

The old widget based pagination did this automagically. So what am I missing? Is this a bug or just not supported?

**Comment by georgringer** [comment]
i suggest to just use addQueryString to your templates as it works. something I miss?

**Comment by sksksksk** [comment]
thanks for the answer Georg. Yes, the addQueryString works for me. I was just wondering if I am doing something work.

IMHO this is worth mentioning in the documentation for people coming from the widget. 

I will close this issue
