### ISSUE TITLE
Cannot access protected property GeorgRinger\NumberedPagination\NumberedPagination::$paginator

### ISSUE THREAD

**Issue by dennismetz** [georgringer/numbered_pagination#2]
I get the following error message since I updated an extension which is based on this one.

Related:
https://github.com/cdaecke/md_news_author/issues/17

Quick fix:
Changed "protected $paginator;" to "public $paginator;" in numbered_pagination/Classes/NumberedPagination.php

**Comment by cdaecke** [comment]
@georgringer Maybe you can publish version 1.0.1 in TER?

**Comment by georgringer** [comment]
done. thanks for reminder

**Comment by dennismetz** [comment]
Thank you!
