### ISSUE TITLE
Styles missing?

### ISSUE THREAD

**Issue by magicsunday** [georgringer/numbered_pagination#20]
Where are the styles? Using predefined partial I got the following ugly result:

- TYPO3: v11.5.26
- numbered_pagination: v1.0.5

![grafik](https://user-images.githubusercontent.com/564393/234572331-ed216855-4e11-4423-8e55-fd2b51d6e0b0.png)

**Comment by georgringer** [comment]
why are those classes better than the current ones? will those fit for more people?

don't get me wrong but IMO those are one of the templates which need to be fixed anyway and always

**Comment by magicsunday** [comment]
The classes does not exist in TYPO3 v11 any more. With this changes a base styling is available for TYPO3 v11, otherwise you have to copy and adjust the template on your own.

Please see also https://github.com/TYPO3/typo3/blob/11.5/typo3/sysext/beuser/Resources/Private/Partials/SimplePagination.html
