### ISSUE TITLE
GET Parameter in pagination-links

### ISSUE THREAD

**Issue by stephangrass** [georgringer/numbered_pagination#24]
I have a list that is filtered through GET parameters. How can I pass this list to the paginator as well?

**Comment by stephangrass** [comment]
Ok, ich habe im Template addQueryString: 1 hinzugefügt. Dann klappt es.

**Comment by heisenbol** [comment]
For anyone getting here with this problem on TYPO3 12.

The addQueryString property basically uses the setAddQueryString() method of uribuilder.
In TYPO3 12, the following change has been made in this method:
"In frontend context, setting this property will only include mapped query arguments from the Page Routing. To include any - possible "unsafe" - GET parameters, the property has to be set to "untrusted"."

Basically this means that in order for this to work with addQueryString=true or 1, the parameters must be mapped in page routing. In my case this was not done like this (complex form with no routing for the various search params). And thus the pagination stopped working. I had to set the value of addQueryString to untrusted. Something like this

<a href="{f:uri.action(action:actionName, arguments:{currentPage: page}, addQueryString:'untrusted')}">{page}</a>
