### ISSUE TITLE
TYPO3 v13 compatibility

### ISSUE THREAD

**Issue by featdd** [georgringer/numbered_pagination#32]
Hi Georg,

could you allow TYPO3 v13 in the version constraint?
I've tested this and there seems to be no breaking changes, as it's working fine for me.

Greetings
Daniel

**Comment by georgringer** [comment]
wanna do a PR? thanks

**Comment by featdd** [comment]
Hi @georgringer,

I didn't thought adding 7 characters would require a pull request but here it is 😅
Thanks for this extension of course also 👍🏻

Greetings
Daniel

**Comment by georgringer** [comment]
Please also change it in the ext_mconf file.

I am currently not on my computer and also bit disabled  
It helps you getting it faster and less work for me, therefore a win win ;)

**Comment by featdd** [comment]
Hi @georgringer,

ah sorry to hear that, I applied the changes to the ext_emconf also now.

Greetings
Daniel

**Comment by georgringer** [comment]
thanks. https://github.com/georgringer/numbered_pagination/releases/tag/2.1.0
