### ISSUE TITLE
What/Where is SimplePagination?

### ISSUE THREAD

**Issue by rowild** [georgringer/numbered_pagination#4]
This docu talks about replacing something called `SimplePagination`. What is that exactly? Where do I find it? Where do I have to place the php code?

**Comment by p380** [comment]
He probably meant this example https://susi.dev/typo3-fluid-paginate/ .
You do not need namespace in your extension.

You only need bellow code:
`$itemsPerPage = 20;
        $maximumLinks = 15;
        $currentPage = $this->request->hasArgument('currentPage') ? (int)$this->request->getArgument('currentPage') : 1;
        $paginator = new \TYPO3\CMS\Extbase\Pagination\QueryResultPaginator($allItems, $currentPage, $itemsPerPage);
        $pagination = new \GeorgRinger\NumberedPagination\NumberedPagination($paginator, $maximumLinks);
        $this->view->assign('pagination', [
            'paginator' => $paginator,
            'pagination' => $pagination,
        ]);`
        
        You replace the variable 'allItems' with your own where you get the data from the repository.
        
        Regards
