### ISSUE TITLE
Missing … if page 1 is not visible

### ISSUE THREAD

**Issue by kanow** [georgringer/numbered_pagination#5]
Hi,

If page 1 in pagination ist not visible if current page is high enough and we have enough pages, then I expected a "…" between the "previous" item and page 2 item. But it's only there if I click on the next page. Only if page 2 is hidden the "…" will be shown.

Is that correct? Here in Code:

`$this->hasLessPages = $this->displayRangeStart > 2;`

This should be 2? Not 1?

**Comment by stigfaerch** [comment]
Yes. The … is missing here:
![Screenshot 2022-03-04 at 08 34 03](https://user-images.githubusercontent.com/6790776/156719768-9e33e89d-c75c-4a89-876d-e414026eae55.png)
