### ISSUE TITLE
Error: Cannot declare interface

### ISSUE THREAD

**Issue by MacGyer** [georgringer/numbered_pagination#9]
Hey guys,

just updated from 1.0.2 to 1.0.3 via Composer and got the following error:

```
  [ TYPO3\CMS\Core\Error\Exception ]                                                                                                       
  Warning: Cannot declare interface TYPO3\CMS\Core\Pagination\PaginationInterface, because the name is already in use in .../typo3conf/ext/numbered_pagination/ext_localconf.php line 8
  ```

TYPO3: 11.5.6
PHP: 7.4.27

**Comment by MacGyer** [comment]
#8

**Comment by georgringer** [comment]
can you recheck with https://github.com/georgringer/numbered_pagination/commit/855c70029fa918ba98a8cee5cc14860e62980b8f?

**Comment by MacGyer** [comment]
Error persists

**Comment by sabbelasichon** [comment]
@MacGyer Could you please locally check if interface_exists instead of class_exists fixes the problem for us. I have introduced this bug. Will fix it asap

**Comment by MacGyer** [comment]
Thx for fixing. Can confirm it's working.
